// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjzdvmqxavqmtmxaupxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqemR2bXF4YXZxbXRteGF1cHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTE0MzMsImV4cCI6MjA3Mjk2NzQzM30.FxsDL8V7EtkF5wpQnVQicHZitC1ti5CG2I0h3fjcP3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});